preprocessing:
  drop_columns:
    - Curricular units 1st sem (enrolled)
    - Educational special needs
    - Curricular units 1st sem (without evaluations)
    - GDP
    - Curricular units 1st sem (credited)
    - Nacionality
    - Curricular units 2nd sem (credited)
    - International
    - Displaced
    - Curricular units 2nd sem (without evaluations)
    - Curricular units 1st sem (approved)
    - Unemployment rate
    - Daytime/evening attendance
  
data_split:
  test_size: 0.2
  random_state: 42

data_paths:
  data_dir_path: data

