preprocessing:
  drop_columns:

    # Redundant / low-importance features
    - Educational special needs
    - GDP
    - Nacionality
    - International
    - Displaced
    - Unemployment rate
    - Daytime/evening attendance
    - Curricular units 1st sem (credited)
    - Curricular units 1st sem (without evaluations)

    # Second semester features (data leakage)
    - Curricular units 2nd sem (credited)
    - Curricular units 2nd sem (enrolled)
    - Curricular units 2nd sem (evaluations)
    - Curricular units 2nd sem (approved)
    - Curricular units 2nd sem (grade)
    - Curricular units 2nd sem (without evaluations)
  
  target_columns:
    - Dropout
    - Enrolled 
    - Graduate
  
data_split:
  test_size: 0.2
  random_state: 42

data_paths:
  data_dir_path: data

