preprocessing:
  drop_columns:

    # Redundant / low-importance features
    - Educational special needs
    - GDP
    - Nacionality
    - International
    - Displaced
    - Unemployment rate
    - Daytime/evening attendance
    - Curricular units 1st sem (credited)
    - Curricular units 1st sem (without evaluations)

    # Second semester features (data leakage)
    - Curricular units 2nd sem (credited)
    - Curricular units 2nd sem (enrolled)
    - Curricular units 2nd sem (evaluations)
    - Curricular units 2nd sem (approved)
    - Curricular units 2nd sem (grade)
    - Curricular units 2nd sem (without evaluations)
  
  target: Target
  target_columns:
    - Dropout
    - Enrolled 
    - Graduate
  
data_split:
  test_size: 0.2
  random_state: 42

data_paths:
  data_dir_path: data

model: 
  model_name: CatBoost
  best_params:
    bootstrap_type: Bayesian
    iterations: 300
    learning_rate: 0.043241532289981156
    depth: 6
    l2_leaf_reg: 8.454092127190801
    random_strength: 0.7724351193852126
    bagging_temperature: 0.4245081819165791
    border_count: 173
    grow_policy: Depthwise
    auto_class_weights: Balanced
    verbose: 0
  random_state: 42
  n_splits: 5
    

